---
title: "Data vis"
author: "Amelia Ritger"
date: "2023-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
devtools::install_github("kraskura/AnalyzeResp", force = TRUE)
library(AnalyzeResp)
```

## R Markdown
```{r}
temp_files <- list.files(here("data", "data"), pattern=".*txt")
temp_all <- data.frame()
for (i in 1:length(temp_files)){
  print(temp_files[i])
  temp_data <- textFileConvert(txt_file = temp_files[i],
                local_path = FALSE,
                type_file = "Firesting_2023",
                N_Ch = 4,
                nrowSkip = 70, # witrox
                convert_units = TRUE,
                units_from = "pct", # units of oxygen measured 
                units_to = "mg/L",
                salinity = 0,
                atm_pressure = 1)
  
  temp_all <- rbind(temp_all, temp_data) #for each iteration, bind the new data to the building dataset
}
temp_all <- temp_all %>%
  clean_names() %>%
  mutate(seconds = row_number(),
         minutes = seconds/60,
         hours = minutes/60)

ggplot(temp_all, aes(x=seconds, y=oxygen))
```

