---
title: "data_supplemental_vis_tables"
author: "Krista Kraskura"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(here)
library(lme4)
library(tidyverse)
library(readxl)
library(janitor)
library(merTools)
library(ggeffects)
theme_set(theme_bw()) # set the default ggplot 

```

```{r}
# *************************************************
# data files from metabolism analysis
list_csv_files <- paste(here("MMR_SMR_AS_EPOC", "csv_analyzed_SMR/"),
                        list.files(path = here("MMR_SMR_AS_EPOC",
                                               "csv_analyzed_SMR")),
                        sep ="")
# compile all data in one dataframe and add filename
data.rmr <- do.call(rbind, lapply(list_csv_files, function(x) cbind(read.csv(x), filename=gsub("^.{114}", "", x))))

# VOLUMES: 
# With tile, probe, and stir bar: 88 mL
# Without tile (but with probe and stir bar): 93 mL 

# rename and organise 
data.rmr<-data.rmr %>% 
  dplyr:::select(ID, Ch, bw, t_mean, mo2,
                 m, min_start, r2, 
                 background_slope, filename, ) %>% 
  rename(BW = bw) %>% 
  mutate(mr_back = abs(background_slope * 0.088), 
         mr_cory = abs(m * 0.088-BW), 
         back_pct = mr_back/mr_cory,
         file_id = paste(gsub("_cory.*", "", gsub("^.{23}", "", filename)), 
                         "_", ID, sep = "")) %>% # volume with tile in ML
  filter(back_pct < 0.8) %>% 
  group_by(file_id) %>% 
  mutate(MR = mean(mo2)*BW,
         min_mo2_mgO2min = min(mo2)*BW,
         max_mo2_mgO2min = max(mo2)*BW,
         n = n())
  
# *************************************************
# master datafile with respirometry trial details
data<-readxl::read_excel(path = here("data/respirometry_info.xlsx"),
                                 sheet = "merged data")
data<- data %>% 
  tidyr::fill(Filename) %>% # fill blanks
  filter(Run == "Corynactis") %>% # exclude empty chamber runs
  mutate(ID = paste(Box, "-", Genet, Tank, "-P", Polyps, sep = "")) %>%  # unique ID same as respo ID 
  rename(sum_mass_g = `Sum body size (g)`) %>% 
  mutate_at(c("Filename", "Alternative filename", "Box", 
              "Genet", "Tank", "Run"), as.factor) %>% 
  mutate_at(c("Temperature", "Polyps", "sum_mass_g"), as.numeric) %>% 
  mutate(Treatment = if_else(Temperature <= 14, "cold",
                             if_else(Temperature > 16, "extreme", "severe")), 
         file_id = paste(gsub("_cory.*", "", gsub("^.{25}", "", Filename)), 
                         "_", ID, sep = "")) # add treatments and ID to merge

# length(levels(factor(data$file_id)))
# length(levels(factor(data.mr$file_id)))
# view(data)
# levels(factor(data$ID)) == levels(factor(data.mr$ID))
# data0<-merge(data, data.mr, by = "file_id")
data0<-merge(data, data.rmr, by = "file_id")

```

Mass scaling and polyp scaling

```{r mass scaling, fig.align='center', fig.width=7, fig.height=2.5}
# scaling figure
p1<-ggplot(data0, aes(x = log(BW), y = log(MR), 
                  color = Genet,
                  fill = Genet,
                  group  = Genet)) +
  geom_point(alpha = 0.3, pch =16)+
  facet_grid(.~Treatment)+
  scale_color_manual(values = genet_cols)+
  scale_fill_manual(values = genet_cols)
p1

# size and treatment
p2<-ggplot(data = data0, aes(x = Genet, y = BW* 1000,
                            color = Genet, 
                            fill = Genet,
                            alpha = Treatment,
                            group = interaction(Treatment, Genet)))+
  geom_boxplot(show.legend = F)+
  geom_point(position = position_dodge(width = 0.75),
             color = "black", pch=21, alpha = 1)+
  scale_color_manual(values = genet_cols)+
  scale_fill_manual(values = genet_cols)

# size and treatment
p3<-ggplot(data = data0, aes(y = BW*1000, x = Polyps,
                            color = Genet, 
                            fill = Genet,
                            group = interaction(Treatment, Genet)))+
  geom_point(pch=16, alpha = 0.4)+
  scale_color_manual(values = genet_cols)+
  scale_fill_manual(values = genet_cols)+
  facet_grid(.~Treatment)+
  stat_smooth(method = "lm", formula = y~poly(x, 2))
p3
cowplot::plot_grid(p1, p2,p3, labels = "AUTO", nrow = 3)



```

